/**
 * All user-facing copy. Centralised for maintainability and future localisation.
 */
export const LABELS = {
  brand: {
    school: "LN International School",
    module: "Parents Portal",
    tagline: "Stay connected with your child's academic journey.",
    location: "Ranchi",
  },
  login: {
    admissionNumber: "Admission Number",
    admissionPlaceholder: "Enter admission number",
    password: "Password",
    passwordPlaceholder: "Enter password",
    forgotPassword: "Forgot Password?",
    submit: "Login",
    submitting: "Signing in…",
    helper: "Use the credentials shared by the school office.",
    version: "Version 1.0.0",
  },
  home: {
    quickAccess: "Quick Access",
    todaysUpdates: "Today's Academic Timeline",
    schoolNotices: "School Notices",
    classNotices: "Class Notices",
    complaintStatus: "Complaint Status",
    gallery: "Gallery",
    seeAll: "See all",
    attendanceTitle: "Today's Attendance",
    attendanceSubtitle: "View details",
    complaintCardTitle: "Complaint Portal",
    complaintCardBody: "Raise a concern and track it privately with the school.",
    notifications: "Notifications",
  },
  work: {
    title: "Academic Work",
    homework: "Homework",
    classwork: "Classwork",
    due: "Due",
    assignedBy: "Assigned by",
    emptyTitle: "Nothing assigned yet",
    emptyBody: "New work shared by teachers will appear here.",
  },
  notices: {
    title: "Notices",
    school: "School Notices",
    class: "Class Notices",
    emptyTitle: "No notices right now",
    emptyBody: "Announcements from the school will show up here.",
  },
  attendance: {
    title: "Attendance",
    comingSoonTitle: "Attendance is coming soon",
    comingSoonBody:
      "We are building a smarter attendance experience. Daily updates, monthly summaries and subject-wise insights will appear right here.",
    monthlySummary: "Monthly Summary",
    calendar: "Monthly Calendar",
    subjectWise: "Subject-wise Attendance",
    notifyMe: "Notify me when it is ready",
  },
  gallery: {
    title: "Gallery",
    emptyTitle: "No photographs yet",
    emptyBody: "School events and classroom moments will be shared here.",
    all: "All",
  },
  complaints: {
    title: "Complaint Portal",
    listTitle: "My Complaints",
    newComplaint: "New Complaint",
    subject: "Subject",
    category: "Category",
    description: "Description",
    submit: "Submit Complaint",
    createdOn: "Created on",
    status: "Status",
    composerPlaceholder: "Type your message…",
    send: "Send",
    emptyTitle: "No complaints raised",
    emptyBody: "When you raise a concern it will be tracked here privately.",
  },
  helpDesk: {
    navLabel: "Help Desk",
    title: "Parents Help Desk",
    intro: "We are here to help",
    introBody:
      "Start a request, call the right desk, or read answers to common questions — all in one place.",
    quickActions: "What do you need help with?",
    newRequest: "New Request",
    myRequests: "My Requests",
    contacts: "School Contacts",
    faqs: "Common Questions",
    threadTitle: "Request",
    emptyTitle: "No requests yet",
    emptyBody: "Raise a request and the school will reply here privately.",
  },
  profile: {
    title: "Profile",
    admissionNumber: "Admission Number",
    parentName: "Parent Name",
    mobileNumber: "Mobile Number",
    classSection: "Class & Section",
    changePassword: "Change Password",
    contactSchool: "Contact School",
    privacyPolicy: "Privacy Policy",
    about: "About",
    logout: "Logout",
  },
  states: {
    offlineTitle: "No Internet Connection",
    offlineBody: "Check your connection and try again. Your data is safe.",
    retry: "Retry",
    errorTitle: "Something went wrong",
    errorBody: "We could not load this section. Please try again.",
    notFoundTitle: "Page not found",
    notFoundBody: "The page you are looking for does not exist or has moved.",
    goHome: "Go to Home",
  },
} as const;
