/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as HelpdeskRouteImport } from './routes/helpdesk'
import { Route as HomeRouteImport } from './routes/home'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ComplaintsIndexRouteImport } from './routes/complaints.index'
import { Route as ComplaintsComplaintIdRouteImport } from './routes/complaints.$complaintId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpdeskRoute = HelpdeskRouteImport.update({
  id: '/helpdesk',
  path: '/helpdesk',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsIndexRoute = ComplaintsIndexRouteImport.update({
  id: '/complaints/',
  path: '/complaints/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsComplaintIdRoute = ComplaintsComplaintIdRouteImport.update({
  id: '/complaints/$complaintId',
  path: '/complaints/$complaintId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/gallery': typeof GalleryRoute
  '/helpdesk': typeof HelpdeskRoute
  '/home': typeof HomeRoute
  '/notices': typeof NoticesRoute
  '/profile': typeof ProfileRoute
  '/work': typeof WorkRoute
  '/complaints/$complaintId': typeof ComplaintsComplaintIdRoute
  '/complaints/': typeof ComplaintsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/gallery': typeof GalleryRoute
  '/helpdesk': typeof HelpdeskRoute
  '/home': typeof HomeRoute
  '/notices': typeof NoticesRoute
  '/profile': typeof ProfileRoute
  '/work': typeof WorkRoute
  '/complaints/$complaintId': typeof ComplaintsComplaintIdRoute
  '/complaints': typeof ComplaintsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/gallery': typeof GalleryRoute
  '/helpdesk': typeof HelpdeskRoute
  '/home': typeof HomeRoute
  '/notices': typeof NoticesRoute
  '/profile': typeof ProfileRoute
  '/work': typeof WorkRoute
  '/complaints/$complaintId': typeof ComplaintsComplaintIdRoute
  '/complaints/': typeof ComplaintsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/gallery'
    | '/helpdesk'
    | '/home'
    | '/notices'
    | '/profile'
    | '/work'
    | '/complaints/$complaintId'
    | '/complaints/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/gallery'
    | '/helpdesk'
    | '/home'
    | '/notices'
    | '/profile'
    | '/work'
    | '/complaints/$complaintId'
    | '/complaints'
  id:
    | '__root__'
    | '/'
    | '/attendance'
    | '/gallery'
    | '/helpdesk'
    | '/home'
    | '/notices'
    | '/profile'
    | '/work'
    | '/complaints/$complaintId'
    | '/complaints/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendanceRoute: typeof AttendanceRoute
  GalleryRoute: typeof GalleryRoute
  HelpdeskRoute: typeof HelpdeskRoute
  HomeRoute: typeof HomeRoute
  NoticesRoute: typeof NoticesRoute
  ProfileRoute: typeof ProfileRoute
  WorkRoute: typeof WorkRoute
  ComplaintsComplaintIdRoute: typeof ComplaintsComplaintIdRoute
  ComplaintsIndexRoute: typeof ComplaintsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helpdesk': {
      id: '/helpdesk'
      path: '/helpdesk'
      fullPath: '/helpdesk'
      preLoaderRoute: typeof HelpdeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints/': {
      id: '/complaints/'
      path: '/complaints'
      fullPath: '/complaints/'
      preLoaderRoute: typeof ComplaintsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints/$complaintId': {
      id: '/complaints/$complaintId'
      path: '/complaints/$complaintId'
      fullPath: '/complaints/$complaintId'
      preLoaderRoute: typeof ComplaintsComplaintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendanceRoute: AttendanceRoute,
  GalleryRoute: GalleryRoute,
  HelpdeskRoute: HelpdeskRoute,
  HomeRoute: HomeRoute,
  NoticesRoute: NoticesRoute,
  ProfileRoute: ProfileRoute,
  WorkRoute: WorkRoute,
  ComplaintsComplaintIdRoute: ComplaintsComplaintIdRoute,
  ComplaintsIndexRoute: ComplaintsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
